packages:
    - name: auto-message-job
      functions:
        - name: auto-message
          limits:
            timeout: 18000
            memory: 1024
          runtime: python:default
          web: false